"""empty message

Revision ID: 006abe24ba96
Revises: aa6212fe03ca
Create Date: 2025-02-16 21:07:52.993771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006abe24ba96'
down_revision = 'aa6212fe03ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
