"""empty message

Revision ID: 030e211ee566
Revises: 3f748a496ec2
Create Date: 2025-04-04 02:50:06.490765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030e211ee566'
down_revision = '3f748a496ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_column('table_type')

    # ### end Alembic commands ###
