"""empty message

Revision ID: 0682fcce1f71
Revises: 030e211ee566
Create Date: 2025-04-04 03:14:23.418869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0682fcce1f71'
down_revision = '030e211ee566'
branch_labels = None
depends_on = None


def upgrade():
    # First set default values for NULL entries
    op.execute("UPDATE layout SET table_type = 'standard' WHERE table_type IS NULL")
    
    # Then add the NOT NULL constraint
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.alter_column('table_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.alter_column('table_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
