"""Add furniture fields to Layout model

Revision ID: 3f748a496ec2
Revises: 008755644a9e
Create Date: 2025-04-04 02:13:36.999918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f748a496ec2'
down_revision = '008755644a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.alter_column('table_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.alter_column('table_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('color')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('name')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
