"""Added menu_orders to Booking and image_url to MenuItem

Revision ID: 54af031cf3a9
Revises: 200b78856648
Create Date: 2025-04-13 07:35:18.489806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54af031cf3a9'
down_revision = '200b78856648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_orders', sa.JSON(), nullable=True))

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('menu_orders')

    # ### end Alembic commands ###
