"""empty message

Revision ID: 73946d14e379
Revises: 4150e69bfe8e
Create Date: 2025-03-20 19:53:45.153428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73946d14e379'
down_revision = '4150e69bfe8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_suggestion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout_version', schema=None) as batch_op:
        batch_op.drop_column('is_suggestion')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
