"""empty message

Revision ID: 7b166a7865b1
Revises: 7bd59bd0ca6e
Create Date: 2025-03-06 20:34:12.123169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b166a7865b1'
down_revision = '7bd59bd0ca6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_cuisine', sa.String(length=100), nullable=True),
    sa.Column('dietary_restrictions', sa.String(length=200), nullable=True),
    sa.Column('ambiance_preference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'num_guests',
                sa.Integer(),
                server_default='1',
                nullable=False
            )
        )
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('special_requests', sa.String(length=300), nullable=True))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_price', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_tier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('loyalty_tier')
        batch_op.drop_column('loyalty_points')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('average_price')
        batch_op.drop_column('capacity')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('special_requests')
        batch_op.drop_column('status')
        batch_op.drop_column('num_guests')

    op.drop_table('user_preference')
    # ### end Alembic commands ###
